parameters:
  no_dev: 'false'
steps:
- bash: |
    sudo composer self-update
    composer global require hirak/prestissimo
    test "${{ parameters.no_dev }}" == "true" && export EXTRA_PARAM = "--no-dev"
    composer install --no-interaction --no-suggest --no-progress --ignore-platform-reqs ${EXTRA_PARAM:-}
  displayName: 'composer install'
