jobs:
- job: build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: step-prepare-environment.yml
  - template: step-composer-install.yml

  - script: yarn global add greenkeeper-lockfile@2
    displayName: Install greenkeeper

  - bash: |
      source scripts/ci/fixsecrets.sh
      $(yarn global bin)/greenkeeper-lockfile-update
    displayName: 'Update yarn lockfile'
    env:
      TRAVIS: true
      TRAVIS_REPO_SLUG: $(Build.Repository.Name)
      TRAVIS_BRANCH: $(System.PullRequest.SourceBranch)
      TRAVIS_PULL_REQUEST: false
      TRAVIS_JOB_NUMBER: .1
      GK_LOCK_YARN_OPTS: --ignore-engines
      GH_TOKEN: $(GH_TOKEN)
      GK_LOCK_DEBUG: true

  - task: CacheBeta@0
    inputs:
      key: yarn-v1 | yarn.lock
      path: $(YARN_CACHE_FOLDER)
    displayName: Cache Yarn packages
  - script: yarn inst
    displayName: 'yarn install'

  - bash: |
      source scripts/ci/fixsecrets.sh
      $(yarn global bin)/greenkeeper-lockfile-upload
      cat gk-lockfile-git-push.err || true
      rm -f gk-lockfile-git-push.err || true
    displayName: 'Upload yarn lockfile'
    env:
      TRAVIS: true
      TRAVIS_REPO_SLUG: $(Build.Repository.Name)
      TRAVIS_BRANCH: $(System.PullRequest.SourceBranch)
      TRAVIS_PULL_REQUEST: false
      TRAVIS_JOB_NUMBER: .1
      GH_TOKEN: $(GH_TOKEN)
      GK_LOCK_DEBUG: true

  # Update js and css assets eventually
  - script: yarn lint
    displayName: 'Check js and vue lint'
  - bash: |
      source scripts/ci/fixsecrets.sh
      scripts/ci/update-assets.sh
    displayName: 'Update assets'
    env:
      ASSETS_USERNAME: $(ASSETS_USERNAME)
      ASSETS_EMAIL: $(ASSETS_EMAIL)
      ASSETS_GITHUB_TOKEN: $(ASSETS_GITHUB_TOKEN)
