parameters:
  no_dev: 'false'

steps:
- task: CacheBeta@0
  inputs:
    key: composer-v2 | composer.lock
    path: $(COMPOSER_HOME)/cache
  displayName: Cache composer packages

- script: composer validate
  displayName: Validate composer files

- ${{ if eq(coalesce(parameters.no_dev, 'false'), 'false') }}:
  - script: 'echo ##vso[task.setvariable variable=EXTRA_PARAM]'
    displayName: Set empty param
- ${{ if ne(coalesce(parameters.no_dev, 'false'), 'false') }}:
  - script: 'echo ##vso[task.setvariable variable=EXTRA_PARAM]--no-dev'
    displayName: Set extra param

- script: composer install --no-interaction --no-suggest --no-progress --ignore-platform-reqs $EXTRA_PARAM
  displayName: composer install
