# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION ||= "2"

$script = <<SCRIPT
MONICA_USER=${MONICA_USER:-admin@admin.com}
MONICA_PASSWORD=${MONICA_PASSWORD:-admin}

DESTDIR=/var/www/html/monica

cd $DESTDIR

echo -e "\n\033[4;32mConfiguring Monica\033[0;40m"

sudo -u www-data php artisan key:generate
sudo -u www-data php artisan setup:production --force --email=$MONICA_USER --password=$MONICA_PASSWORD
sudo -u www-data php artisan passport:install

echo -e "\n\n\033[1;32mDone! You can access Monica by visiting \033[4;96mhttp://localhost:8080\033[0;40m\033[1;32m from your host machine\033[0;40m"

SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "monicahq/monicahq"
  config.vm.hostname = "monica"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "shell", inline: $script, keep_color: true
end